[project]
name = "kokoros"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "numpy>=1.24.0",
  "openai>=1.61.1",
  "requests>=2.31.0",
  "torch>=2.0.0",
]
